FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y gcc && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    pandas \
    requests \
    python-dotenv \
    clickhouse-connect \
    kafka-python